# Настройка рабочей среды, работа с Git, структура репозитория и базовые операции в NumPy.

In [3]:
# Импорт библиотеки NumPy с общепринятым сокращением.
import numpy as np

In [ ]:
# Примеры создания массивов:
array1 = [7, 312, 12, -1, 4.3]
array2 = np.zeros((3, 6))
array3 = np.ones((6,3))
array4 = np.arange(15, 32, 2)

In [7]:
# Демонстрация атрибутов:
print(array4.shape) # Форма массива
print(array4.dtype) # Тип данных элементов массива

(9,)
int64


In [ ]:
# Примеры индексирования и срезов:
print(array1[3]) #4ый элемент
print(array4[2:6])

-1
[19 21 23 25]


In [10]:
# Примеры векторных операций и базовых статистик:
print(array2 + 2)  # Сложение со скаляром 
print(np.median(array4))  # Медиана массива

[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]
23.0
